---
title: "Reproducibility Report for Study by Salamons et al. (2026, Animal Behaviour)"
author: "Samantha Kefer (skefer@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  pdf:
    toc: true
    toc_depth: 3
---

<!-- Reproducibility reports should all use this template to standardize reporting across projects. These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

[No abstract is needed.]  Each reproducibility project will have a straightforward, no frills report of the study and reproducibility results. These reports will be publicly available as supplementary material for the aggregate report(s) of the project as a whole.  Also, to maximize project integrity, the intro and methods will be written and critiqued in advance of your attempt to reproduce the results. Introductions can be just 1-2 paragraphs clarifying the main idea of the original study, the target finding for your reproducibility attempt, and any other essential information.  It will NOT have a literature review -- that is in the original publication. You can write both the introduction and the methods in past tense.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Justification for choice of study

The paper by Salomons et al. explains the cognitive development of assistance puppies (aged 8 to 20 weeks) as measured through performance on 9 tasks: marker gesture, working memory, working memory with distraction, auditory discrimination, odor discrimination, cylinder (inhibitory control and reversal learning), unsolvable, causal reasoning, and momentary pointing. The results support the multiple intelligences hypothesis and suggest the emergence of distinct cognitive abilities, with clear developmental breakpoints in marker gesture comprehension, inhibitory control, reversal learning, and eye contact occurring before 16 weeks, coinciding with the period of rapid brain development. I am currently working to develop a battery of tests that can be administered to large numbers of dogs, in the hopes of identifying exceptional performers and determining whether strong performance on one task may generalize across different measures of the same ability and/or across cognitive domains. By reanalyzing these data to ensure reproducibility and simulating additional data to see how these patterns appear in a larger sample, I hope to gain further insights that may aid in the creation of a novel dog cognition battery; with the help of citizen science, this method may ultimately identify exceptional dogs.

### Anticipated challenges

As explained above, my plan for this project includes (1) reanalyzing existing data and (2) simulating additional subjects. To reproduce Figure 2, I will plot proportion correct or mean looking time against age, with a LOESS curve for each of the 11 variables. Next, I will use mixed-effects logistic regression models for the 10 correct/incorrect measures and a mixed-effects linear regression for looking time, with subject ID as a random effect, and compare AIC values across models incorporating age, sex, experience, and rearing. Finally, I will test each age group against 50% to determine the age at which each skill emerges and use Mann-Whitney U tests to compare longitudinal and control puppies. The goal of my simulation is to create 1000 'artificial puppies,' use these same analyses, and compare to the original data.* This would require generating 40 trial outcomes per dog per testing session (10 tasks with 4 trials each), based on the puppy's performance at each age. I will then check the simulated curves against the original Figure 2 and whether the simulated estimates resemble the real data.

I anticipate running into a few challenges when attempting to reproduce these results. First, age and experience are highly intertwined since they increase together for all longitudinal subjects. In addition, many of the dogs are siblings, half-siblings, cousins, etc. and this relatedness is not included in the dataset and may be a confound. The biggest challenge, however, will be actually completing this project given my minimal programming knowledge and experience.  

"*" I am currently debating if it makes more sense to simulate 1000 puppies (larger sample size) or 1000 datasets (better answers replicablility)

### Links

Project repository (on Github): https://github.com/samkefer/salomons2026/tree/main

Original paper (as hosted in your repo): https://github.com/samkefer/salomons2026/blob/main/original_paper/original_paper

## Methods

### Description of the steps required to reproduce the results

Please describe all the steps necessary to reproduce the key result(s) of this study. 

### Differences from original study

Explicitly describe known differences in the analysis pipeline between the original paper and yours (e.g., computing environment). The goal, of course, is to minimize those differences, but differences may occur. Also, note whether such differences are anticipated to influence your ability to reproduce the original results.

## Project Progress Check 1

### Measure of success

Please describe the outcome measure for the success or failure of your reproduction and how this outcome will be computed.


### Pipeline progress

Earlier in this report, you described the steps necessary to reproduce the key result(s) of this study. Please describe your progress on each of these steps (e.g., data preprocessing, model fitting, model evaluation).


## Results

### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Key analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Reproduction Attempt

Open the discussion section with a paragraph summarizing the primary result from the key analysis and assess whether you successfully reproduced it, partially reproduced it, or failed to reproduce it.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis of the dataset, (b) assessment of the meaning of the successful or unsuccessful reproducibility attempt - e.g., for a failure to reproduce the original findings, are the differences between original and present analyses ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the reproducibility attempt (if you contacted them).  None of these need to be long.
